> test info

test suite: `nbomber_default_test_suite_name`

test name: `nbomber_default_test_name`

session id: `2023-02-12_22.11.42_session_2af1d57d`

> scenario stats

scenario: `WeatherForecast`

  - ok count: `95989`

  - fail count: `11`

  - all data: `53.2568` MB

  - duration: `00:02:00`

load simulations:

  - `inject_per_sec`, rate: `800`, during: `00:02:00`

step: `GetWeatherForecastGrpc`

  - timeout: `1000` ms

  - client factory: `nbomber_http_factory`, clients: `1`

  - data feed: `none`

|step|ok stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `96000`, ok = `95989`, RPS = `799.9`|
|latency|min = `136.74`, mean = `499.03`, max = `940.31`, StdDev = `220.14`|
|latency percentile|50% = `491.52`, 75% = `698.37`, 95% = `845.82`, 99% = `867.33`|
|data transfer|min = `0.551` KB, mean = `0.567` KB, max = `0.588` KB, all = `53.2568` MB|


|step|fail stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `96000`, fail = `11`, RPS = `0.1`|
|latency|min = `37.83`, mean = `40.41`, max = `58.92`, StdDev = `5.88`|
|latency percentile|50% = `38.56`, 75% = `39.14`, 95% = `39.58`, 99% = `58.94`|


> status codes for scenario: `WeatherForecast`

|status code|count|message|
|---|---|---|
|200|95989||
|-101|11|step unhandled exception: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (perf-main-api-lnx-vnet-goetw36e4h7di.azurewebsites.net:443))|


