> test info

test suite: `nbomber_default_test_suite_name`

test name: `nbomber_default_test_name`

session id: `2023-02-12_22.17.00_session_fce11880`

> scenario stats

scenario: `WeatherForecast`

  - ok count: `95793`

  - fail count: `207`

  - all data: `53.1506` MB

  - duration: `00:02:00`

load simulations:

  - `inject_per_sec`, rate: `800`, during: `00:02:00`

step: `GetWeatherForecastGrpc`

  - timeout: `1000` ms

  - client factory: `nbomber_http_factory`, clients: `1`

  - data feed: `none`

|step|ok stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `96000`, ok = `95793`, RPS = `798.3`|
|latency|min = `134.06`, mean = `491.8`, max = `1014.16`, StdDev = `219.22`|
|latency percentile|50% = `485.12`, 75% = `692.22`, 95% = `836.1`, 99% = `873.47`|
|data transfer|min = `0.552` KB, mean = `0.567` KB, max = `0.588` KB, all = `53.1506` MB|


|step|fail stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `96000`, fail = `207`, RPS = `1.7`|
|latency|min = `22.82`, mean = `963.98`, max = `1029.81`, StdDev = `201.4`|
|latency percentile|50% = `1008.64`, 75% = `1018.37`, 95% = `1028.61`, 99% = `1030.14`|


> status codes for scenario: `WeatherForecast`

|status code|count|message|
|---|---|---|
|200|95793||
|-101|11|step unhandled exception: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (perf-main-api-lnx-vnet-goetw36e4h7di.azurewebsites.net:443))|
|-100|196|step timeout: 1000 ms|


