> test info

test suite: `nbomber_default_test_suite_name`

test name: `nbomber_default_test_name`

session id: `2023-02-12_22.14.84_session_54cacef8`

> scenario stats

scenario: `WeatherForecast`

  - ok count: `41525`

  - fail count: `66475`

  - all data: `23.0397` MB

  - duration: `00:02:00`

load simulations:

  - `inject_per_sec`, rate: `900`, during: `00:02:00`

step: `GetWeatherForecastGrpc`

  - timeout: `1000` ms

  - client factory: `nbomber_http_factory`, clients: `1`

  - data feed: `none`

|step|ok stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `108000`, ok = `41525`, RPS = `346`|
|latency|min = `198.68`, mean = `755.6`, max = `1381.9`, StdDev = `179.05`|
|latency percentile|50% = `768`, 75% = `897.54`, 95% = `1006.08`, 99% = `1106.94`|
|data transfer|min = `0.552` KB, mean = `0.567` KB, max = `0.589` KB, all = `23.0397` MB|


|step|fail stats|
|---|---|
|name|`GetWeatherForecastGrpc`|
|request count|all = `108000`, fail = `66475`, RPS = `554`|
|latency|min = `117.28`, mean = `1009.31`, max = `1386.67`, StdDev = `144.82`|
|latency percentile|50% = `1022.46`, 75% = `1043.46`, 95% = `1114.11`, 99% = `1254.4`|


> status codes for scenario: `WeatherForecast`

|status code|count|message|
|---|---|---|
|200|41525||
|-101|3280|step unhandled exception: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (perf-main-api-lnx-vnet-goetw36e4h7di.azurewebsites.net:443))|
|-100|63195|step timeout: 1000 ms|


